version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/joway/libimagequant-go
    steps:
      - checkout
      - run: sudo apt update && sudo apt install -y gcc
      - run: env GO111MODULE=on go mod download
      - run: env GO111MODULE=on go mod vendor
      - run: env GO111MODULE=on go mod verify
      - run: env GO111MODULE=on go test -v ./...
  install:
    docker:
      - image: circleci/golang:1.11
    steps:
      - run: mkdir -p ~/.ssh/ && ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: go get -u github.com/joway/libimagequant-go/pngquant
workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - install
